apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: jandersolutions/projeto-k8s-database:1.0
          imagePullPolicy: Always
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
              name: mysql

          volumeMounts:
            - name: local
              mountPath: /var/lib/mysql
      volumes:
        - name: local
          hostPath:
            path: /database/data/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: jandersolutions/projeto-k8s-backend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
